### ISSUE TITLE
Split out core classes.

### ISSUE THREAD

**Issue by wcmatthysen** [NASAWorldWind/WorldWindJava#29]
I have worked a bit with both the WorldWindJava and WorldWindAndroid code-bases. I have noticed that there are some significant code duplication between the projects (e.g. the geom package) which is understandable. Just an idea: wouldn't it be better to have a separate project (e.g. WorldWindCore or WorldWindAPI) that contains the shared platform-agnostic classes for these two projects?

**Comment by zglueck** [comment]
Hey @wcmatthysen thanks for bringing this up. On the surface a "WorldWindCore" does sound like a good idea and way to synchronize some of the platform independent APIs (like geom). The reason the SDKs haven't used this approach is to accommodate the performance differences of their respective platforms. WorldWindJava is written with significant influence of Bloch's "Effective Java" where a core assumption is short lived object creation and destruction is cheap. We've found this assumption isn't as applicable in the Android environment and with the large number of operations conducted during a frame render, may impact the frame time due to garbage collections. For example, Android geom objects tend to be mutable to reduce the creation of new objects where as WorldWindJava's are often immutable and create new instances for each operation. Changing Android to the immutable approach would cause performance issues and changing Java to the mutable approach significantly changes the API and SDK users expectations.

There was an earlier attempt to port WorldWindJava to Android that highlighted the object creation/destruction issue. One of the primary focuses of the Android SDK is to maintain performance and limiting the number of allocations really seems to help on the platform.

While geom may not be a good candidate for unification, perhaps there are some other packages. I'll leave this open and when and if the team has some extra time, maybe we can identify some packages appropriate for a "core" and see if there would be benefit. Our long term goal/desire would be to actually pull back some of Android's approaches to WWJ, but, there really isn't a specific timeline or plan for doing that.

**Comment by wcmatthysen** [comment]
Ok, I understand. It seems much more complex now that you mentioned all of the issues.
